### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [amandp13/Cool-Scripts-Python-Nerds#85]
👋 Hi @amandp13 ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/amandp13/Cool-Scripts-Python-Nerds/issues/86
- [x] https://github.com/amandp13/Cool-Scripts-Python-Nerds/issues/87
- [x] https://github.com/amandp13/Cool-Scripts-Python-Nerds/issues/88
- [x] https://github.com/amandp13/Cool-Scripts-Python-Nerds/issues/89

**Comment by amandp13** [comment]
Hello @ericdrosado Sir,
It's my pleasure to have you as my mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project.
I am looking forward to collaborating with you to help the other students to learn and add contributions to this project. 
Please Let me know how can I be more helpful.
Thank You, Sir.

**Comment by ericdrosado** [comment]
@amandp13 I will reach out next week with next steps!

**Comment by amandp13** [comment]
@ericdrosado Any Updates?

**Comment by ericdrosado** [comment]
👋 Hi @amandp13 I see you have already submitted your repository. You are all set!
